# Generated by Django 4.2.2 on 2023-07-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction_web_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="code",
            field=models.CharField(
                default="DEFAULT", max_length=30, verbose_name="codigo"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="unit",
            field=models.CharField(default="UNIT", max_length=5, verbose_name="unidad"),
        ),
    ]
