# Generated by Django 4.2.2 on 2023-07-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("construction_web_app", "0004_material_subtrade_material_trade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Partida",
                "verbose_name_plural": "Partidas",
            },
        ),
        migrations.CreateModel(
            name="Subtrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="construction_web_app.trade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subpartida",
                "verbose_name_plural": "Subpartidas",
            },
        ),
        migrations.AlterField(
            model_name="material",
            name="subtrade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="construction_web_app.subtrade",
                verbose_name="subpartida",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="trade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="construction_web_app.trade",
                verbose_name="partida",
            ),
        ),
    ]
