# Generated by Django 4.2.2 on 2023-07-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction_web_app", "0002_material_code_material_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="price",
        ),
        migrations.AddField(
            model_name="material",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="precio unitario",
            ),
        ),
    ]
