# Generated by Django 4.2.2 on 2023-07-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction_web_app", "0003_remove_material_price_material_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="subtrade",
            field=models.CharField(
                default="SUBPARTIDA", max_length=100, verbose_name="subpartida"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="trade",
            field=models.CharField(
                default="PARTIDA", max_length=100, verbose_name="partida"
            ),
        ),
    ]
